version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5500:5432"
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ubirockteam@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
  golang:
    build:
      context: ./app
      dockerfile: Dockerfile # Ensure this Dockerfile is located within the ./app directory
    container_name: go_app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app
volumes:
  postgres:
